define(["dojo/_base/declare","dijit/TitlePane","dojo/dom-style"],function(_1,_2,_3){
return _1("rosten.widget.TitlePane",_2,{moreText:"more",moreUrl:"",titleCount:"",showTitleCount:true,width:"",height:"",marginBottom:null,templateString:"<div class=\"dijitTitlePane\">"+"    <div class=\"dijitTitlePaneTitle\" data-dojo-attach-point=\"titleBarNode\" style=\"cursor: default;padding-top:5px\">"+"<span dojoAttachEvent=\"onclick:toggle,onkeypress: _onTitleKey\" tabindex=\"0\""+"role=\"button\" data-dojo-attach-point=\"focusNode,arrowNode\" style=\"cursor: pointer;\">"+"<img src=\"${_blankGif}\" alt=\"\" class=\"dijitArrowNode\" role=\"presentation\"/>"+"<span data-dojo-attach-point=\"arrowNodeInner\" class=\"dijitArrowNodeInner\"></span>"+"</span>"+"<span data-dojo-attach-point=\"titleNode\" class=\"dijitTitlePaneTextNode\"></span>"+"<span data-dojo-attach-point=\"titleCountNode\" class=\"dijitTitlePaneCountNode\"></span>"+"<span style=\"float:right;cursor:pointer;\" data-dojo-attach-point=\"moreNode\" data-dojo-attach-event=\"onclick:_moreClick\"> </span>"+"</div>"+"<div class=\"dijitTitlePaneContentOuter\" data-dojo-attach-point=\"hideNode\">"+"<div class=\"dijitReset\" data-dojo-attach-point=\"wipeNode\">"+"<div class=\"dijitTitlePaneContentInner\" data-dojo-attach-point=\"containerNode\" role=\"region\" tabindex=\"-1\">"+"</div>"+"</div>"+"</div>"+"</div>",postCreate:function(){
rosten.widget.TitlePane.superclass.postCreate.apply(this,arguments);
if(this.marginBottom!=null){
_3.set(this.domNode,{"marginBottom":this.marginBottom});
}
if(!this.toggleable){
_3.set(this.arrowNode,"display","none");
}
if(this.width!=""){
_3.set(this.domNode,{"width":this.width});
}
if(this.height!=""){
_3.set(this.containerNode,{"height":this.height});
}
if(this.moreNode!=""){
this.moreNode.innerHTML=this.moreText;
}
if(this.titleCount!=""){
this.titleCountNode.innerHTML=this.titleCount;
}
if(!this.showTitleCount){
_3.set(this.titleCountNode,"display","none");
}
},changeWidth:function(){
_3.set(this.domNode,{"width":this.width});
},changeHeight:function(){
_3.set(this.containerNode,{"height":this.height});
},changeTitleCount:function(_4){
this.titleCount=_4;
this.titleCountNode.innerHTML=_4;
},_moreClick:function(){
if(this.moreUrl!=""&&this.moreNode!=""){
window.open(this.moreUrl,"_blank");
}
}});
});

